#pragma config(Sensor, dgtl1,  rTracker,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  lTracker,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  hTracker,       sensorQuadEncoder)
#pragma config(Motor,  port2,           driveL1,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           driveL2,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           driveR1,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           driveR2,       tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float x;
float y;
float theta;

#include "miscFunctions.h"
#include "PIDstruct.h"
#include "PID.h"
#include "posControl.h"

task main()
{
	x = y = theta = 0;
	startTask(trackPos);

	moveTo(30,40);

}
